name: Bug Report
description: Create a bug report for the tRPC core
title: "[BUG]: "
labels: "unconfirmed bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please provide any information you deem applicable for reproduction of the encountered bug, e.g. versions of `Node` and `tRPC`, `browser` and `OS` etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please describe the bug as clear and concise as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please describe the behavior you were expecting when encountering the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Describe how to reproduce your bug. Can be either code or a link to a reproduction repo, Stackblitz etc.
  - type: checkboxes
    attributes:
      label: We love contributors in any shape or form. Would you be willing to implement a bugfix?
      options:
        - label: Yes, I'd be down to file a PR fixing this bug!
