name: Bug Report
description: Create a bug report for the Next.js core
labels: "template: bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
