name: 🐞 Bug Report
description: Create a bug report for the tRPC core
title: "[BUG]: "
labels: ["❓ unconfirmed bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
        Note that the more precise you are, the quicker we will be able to investigate the bug.
  - type: textarea
    attributes:
      label: Provide environment information
      description: |
        Run this command in your project root and paste the results:

        ```terminal
        npx envinfo --system --binaries --browsers --npmPackages "next,react,@trpc/server,@trpc/client,@trpc/react,@trpc/client,@trpc/next,react-query"
        ```
      placeholder: |
        ``` 
        <Paste result here> 
        ```

    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please describe the bug as clear and concise as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please describe the behavior you were expecting when encountering the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Describe how to reproduce your bug. Can be either code or a link to a reproduction repo, Stackblitz etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the bug here.
  - type: checkboxes
    attributes:
      label: 👨‍👧‍👦 We love contributors in any shape or form. Would you be willing to implement a bugfix?
      options:
        - label: 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!
